#!/bin/sh
echo "**************************************************"
echo "                                                  "
echo " MovieArchiver by svox                            "
echo "                                                  "
echo "**************************************************"
echo "                                                  "
echo " Plugin successfully installed!                   "
echo "                                                  "
echo " Please restart enigma2 now.		                "
echo "                                                  "
echo "**************************************************"
exit 0
