#!/bin/sh
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/MovieArchiver
echo "                                                          "
echo "        ...MovieArchiver successful removed.              "
echo "             Please restart enigma2 now.		            "
exit 0
