#!/bin/sh
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/MovieArchiver
echo "**************************************************"
echo "                                                  "
echo " MovieArchiver by svox                            "
echo "                                                  "
echo "**************************************************"
echo "                                                  "
echo " Plugin successfully installed!                   "
echo " Please restart enigma2 now.		                "
echo "                                                  "
echo "**************************************************"